### ISSUE TITLE
/pos can escape to other folders.

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/tsuserver3#118]
Strange and somewhat buggy behavior, probably unintended to be able to escape into the file system.

To replicate: /pos ../../characters/phoenix/(a)zoom.apng or something similar. 
Can be used to bypass character passwording and the like in a janky way.

Fix should just be to restrict positions escaping their current folder.

**Comment by Crystalwarrior** [comment]
totally intentional :^)

~~not really, the proposed fix makes sense, simply reject any input that uses ../ as pos path. Though I still low key want /pos_lock ../\<bg\>/pos to be possible...~~

**Comment by Crystalwarrior** [comment]
Actually, just realized that the actual proper solution is to backport /pos_lock system from KFO-Server into tsuserver3 so that GMs and server owners can define their own restrictions on pos instead of doing weird stripping mumbo jumbo. Maybe server owners want to have escaped pos for whatever reason.

**Comment by collinxchu** [comment]
Sanitize your inputs, fat.

**Comment by ApolloBrandonium** [comment]
Definitely an intended feature

**Comment by oldmud0** [comment]
Should be fixed clientside.
