### ISSUE TITLE
/blockdj crashes on use

### ISSUE THREAD

**Issue by Chrezm** [AttorneyOnline/tsuserver3#90]
(submitted on behalf of Stryquill)
**Describe what happened. Please be as descriptive as possible:** A moderator was trying to /blockdj a player with ID 4 via `/blockdj 4`, but kept getting `You must enter a number. Use /blockdj <id>.`

**Describe what you expected should have happened:** The mod should have blockdj'd client 4.

**Do you know what version your server is running? If so, include it:** Tsuserver3.3, fresh installation

**Did this error give you some logging information or messages? If so, please attach it**: Through additional debugging, the error came to be 'NameError: name 'TargetType' is not defined'

**Do you have any additional comments that you feel could be useful?:** Bug fix in comment.

**Comment by Chrezm** [comment]
The bug is caused by /blockdj referring to an uninitialized variable TargetType. This is usually imported from server.constants, but in `music.py` this was overlooked. A similar issue affects `/unblockdj`

**Comment by caleb-mabry** [comment]
Can we mark this issue as closed so other developers don't spend time trying to solve it? The issue was resolved by @stonedDiscord Mar 19, 2020
[The link to the commit is here](https://github.com/AttorneyOnline/tsuserver3/commit/98c17e6c12c961c0ec4a6457b1401f7ec2c7eb79)

Issue is as @Chrezm described in the above comment. Testing this proves that the issue has been resolved.
![image](https://user-images.githubusercontent.com/36182383/105450856-63b36000-5c49-11eb-9bdd-fa73c76bf465.png)
